name: CVE PR Check

on:
  pull_request:
    paths:
      - "cves/*.yaml"
      - "cves/*.json"
      - "announce/*.txt"

permissions:
  contents: read

jobs:
  check-cves:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Fetch PR base commit
        run: |
          set -euo pipefail
          base_sha="${{ github.event.pull_request.base.sha }}"
          if ! git cat-file -e "${base_sha}^{commit}" 2>/dev/null; then
            git fetch --no-tags --depth=1 origin "${base_sha}"
          fi

      - name: Check changed CVEs with cna (flake)
        id: cna_check
        shell: bash
        run: |
          set -euo pipefail

          base_sha="${{ github.event.pull_request.base.sha }}"
          head_sha="${{ github.event.pull_request.head.sha }}"

          if ! changed_raw="$(git diff --name-only "${base_sha}...${head_sha}" -- 'cves/*.yaml' 'cves/*.json' 'announce/*.txt')"; then
            echo "Failed to compute changed CVE files for range ${base_sha}...${head_sha}" >&2
            exit 1
          fi

          mapfile -t changed < <(printf '%s\n' "$changed_raw" | sed '/^$/d')

          if [ "${#changed[@]}" -eq 0 ]; then
            echo "No changed CVE files in this PR."
            exit 0
          fi

          printf 'Changed CVE files:\n'
          printf '  - %s\n' "${changed[@]}"

          mapfile -t cves < <(
            printf '%s\n' "${changed[@]}" \
              | sed -nE 's#^(cves|announce)/(CVE-[0-9]{4}-[0-9]{4,19})\.(yaml|json|txt)$#\2#p' \
              | sort -u
          )

          status=0
          summary_tmp="$(mktemp)"
          echo "## CVE PR Check results" > "$summary_tmp"

          for cve in "${cves[@]}"; do
            echo
            echo "Checking $cve"
            out_tmp="$(mktemp)"
            echo "::group::check $cve"
            if ! nix run github:CPAN-Security/cna-tool#cna -- \
              check "$cve" --format github --pr-policy --base-sha "$base_sha" \
              2>&1 | tee "$out_tmp"; then
              status=1
            fi
            echo "::endgroup::"

            errors="$(grep -c '^::error ' "$out_tmp" || true)"
            warnings="$(grep -c '^::warning ' "$out_tmp" || true)"
            echo "- \`$cve\`: **${errors} error(s)**, ${warnings} warning(s)" >> "$summary_tmp"
            if [ "$errors" -gt 0 ]; then
              echo "  - Blocking findings:" >> "$summary_tmp"
              grep '^::error ' "$out_tmp" \
                | sed -E 's/^::error [^:]*::/- /' >> "$summary_tmp" || true
            fi
            if [ "$warnings" -gt 0 ]; then
              echo "  - Warnings:" >> "$summary_tmp"
              grep '^::warning ' "$out_tmp" \
                | sed -E 's/^::warning [^:]*::/- /' >> "$summary_tmp" || true
            fi
            rm -f "$out_tmp"
          done

          cat "$summary_tmp" >> "$GITHUB_STEP_SUMMARY"
          cp "$summary_tmp" .cna-pr-summary.md
          rm -f "$summary_tmp"

          if [ "$status" -ne 0 ]; then
            echo "::error title=CVE PR check failed::Blocking CVE findings found. See Step Summary."
          fi

          exit "$status"
